export const countries = [
    
    {country: "Afghanistan"},
    {country: "Albania"},
    {country: "Algeria"},
    {country: "American Samoa"},
    {country: "Andorra"},
    {country: "Angola"},
    {country: "Anguilla"},
    {country: "Antigua and Barbuda"},
    {country: "Argentina"},
    {country: "Armenia"},
    {country: "Aruba"},
    {country: "Australia"},
    {country: "Austria"},
    {country: "Azerbaijan"},
    {country: "Bahamas, The"},
    {country: "Bahrain"},
    {country: "Bangladesh"},
    {country: "Barbados"},
    {country: "Belarus"},
    {country: "Belgium"},
    {country: "Belize"},
    {country: "Benin"},
    {country: "Bermuda"},
    {country: "Bhutan"},
    {country: "Bolivia"},
    {country: "Bonaire, Sint Eustatius, and Saba"},
    {country: "Bosnia and Herzegovina"},
    {country: "Botswana"},
    {country: "Brazil"},
    {country: "Brunei"},
    {country: "Bulgaria"},
    {country: "Burkina Faso"},
    {country: "Burma"},
    {country: "Burundi"},
    {country: "Cabo Verde"},
    {country: "Cambodia"},
    {country: "Cameroon"},
    {country: "Canada"},
    {country: "Cayman Islands"},
    {country: "Central African Republic"},
    {country: "Chad"},
    {country: "Chile"},
    {country: "China"},
    {country: "Christmas Island"},
    {country: "Colombia"},
    {country: "Comoros"},
    {country: "Congo (Brazzaville)"},
    {country: "Congo (Kinshasa)"},
    {country: "Cook Islands"},
    {country: "Costa Rica"},
    {country: "Croatia"},
    {country: "Cuba"},
    {country: "Curaçao"},
    {country: "Cyprus"},
    {country: "Czechia"},
    {country: "Côte d’Ivoire"},
    {country: "Denmark"},
    {country: "Djibouti"},
    {country: "Dominica"},
    {country: "Dominican Republic"},
    {country: "Ecuador"},
    {country: "Egypt"},
    {country: "El Salvador"},
    {country: "Equatorial Guinea"},
    {country: "Eritrea"},
    {country: "Estonia"},
    {country: "Eswatini"},
    {country: "Ethiopia"},
    {country: "Falkland Islands (Islas Malvinas)"},
    {country: "Faroe Islands"},
    {country: "Fiji"},
    {country: "Finland"},
    {country: "France"},
    {country: "French Guiana"},
    {country: "French Polynesia"},
    {country: "Gabon"},
    {country: "Gambia, The"},
    {country: "Gaza Strip"},
    {country: "Georgia"},
    {country: "Germany"},
    {country: "Ghana"},
    {country: "Gibraltar"},
    {country: "Greece"},
    {country: "Greenland"},
    {country: "Grenada"},
    {country: "Guadeloupe"},
    {country: "Guam"},
    {country: "Guatemala"},
    {country: "Guernsey"},
    {country: "Guinea"},
    {country: "Guinea-Bissau"},
    {country: "Guyana"},
    {country: "Haiti"},
    {country: "Honduras"},
    {country: "Hong Kong"},
    {country: "Hungary"},
    {country: "Iceland"},
    {country: "India"},
    {country: "Indonesia"},
    {country: "Iran"},
    {country: "Iraq"},
    {country: "Ireland"},
    {country: "Isle of Man"},
    {country: "Israel"},
    {country: "Italy"},
    {country: "Jamaica"},
    {country: "Japan"},
    {country: "Jersey"},
    {country: "Jordan"},
    {country: "Kazakhstan"},
    {country: "Kenya"},
    {country: "Kiribati"},
    {country: "Korea, North"},
    {country: "Korea, South"},
    {country: "Kosovo"},
    {country: "Kuwait"},
    {country: "Kyrgyzstan"},
    {country: "Laos"},
    {country: "Latvia"},
    {country: "Lebanon"},
    {country: "Lesotho"},
    {country: "Liberia"},
    {country: "Libya"},
    {country: "Liechtenstein"},
    {country: "Lithuania"},
    {country: "Luxembourg"},
    {country: "Macau"},
    {country: "Madagascar"},
    {country: "Malawi"},
    {country: "Malaysia"},
    {country: "Maldives"},
    {country: "Mali"},
    {country: "Malta"},
    {country: "Marshall Islands"},
    {country: "Martinique"},
    {country: "Mauritania"},
    {country: "Mauritius"},
    {country: "Mayotte"},
    {country: "Mexico"},
    {country: "Micronesia, Federated States of"},
    {country: "Moldova"},
    {country: "Monaco"},
    {country: "Mongolia"},
    {country: "Montenegro"},
    {country: "Montserrat"},
    {country: "Morocco"},
    {country: "Mozambique"},
    {country: "Namibia"},
    {country: "Nauru"},
    {country: "Nepal"},
    {country: "Netherlands"},
    {country: "New Caledonia"},
    {country: "New Zealand"},
    {country: "Nicaragua"},
    {country: "Niger"},
    {country: "Nigeria"},
    {country: "Niue"},
    {country: "Norfolk Island"},
    {country: "North Macedonia"},
    {country: "Northern Mariana Islands"},
    {country: "Norway"},
    {country: "Oman"},
    {country: "Pakistan"},
    {country: "Palau"},
    {country: "Panama"},
    {country: "Papua New Guinea"},
    {country: "Paraguay"},
    {country: "Peru"},
    {country: "Philippines"},
    {country: "Pitcairn Islands"},
    {country: "Poland"},
    {country: "Portugal"},
    {country: "Puerto Rico"},
    {country: "Qatar"},
    {country: "Reunion"},
    {country: "Romania"},
    {country: "Russia"},
    {country: "Rwanda"},
    {country: "Saint Barthelemy"},
    {country: "Saint Helena, Ascension, and Tristan da Cunha"},
    {country: "Saint Kitts and Nevis"},
    {country: "Saint Lucia"},
    {country: "Saint Martin"},
    {country: "Saint Pierre and Miquelon"},
    {country: "Saint Vincent and the Grenadines"},
    {country: "Samoa"},
    {country: "San Marino"},
    {country: "Sao Tome and Principe"},
    {country: "Saudi Arabia"},
    {country: "Senegal"},
    {country: "Serbia"},
    {country: "Seychelles"},
    {country: "Sierra Leone"},
    {country: "Singapore"},
    {country: "Sint Maarten"},
    {country: "Slovakia"},
    {country: "Slovenia"},
    {country: "Solomon Islands"},
    {country: "Somalia"},
    {country: "South Africa"},
    {country: "South Georgia And South Sandwich Islands"},
    {country: "South Georgia and South Sandwich Islands"},
    {country: "South Sudan"},
    {country: "Spain"},
    {country: "Sri Lanka"},
    {country: "Sudan"},
    {country: "Suriname"},
    {country: "Svalbard"},
    {country: "Sweden"},
    {country: "Switzerland"},
    {country: "Syria"},
    {country: "Taiwan"},
    {country: "Tajikistan"},
    {country: "Tanzania"},
    {country: "Thailand"},
    {country: "Timor-Leste"},
    {country: "Togo"},
    {country: "Tonga"},
    {country: "Trinidad and Tobago"},
    {country: "Tunisia"},
    {country: "Turkey"},
    {country: "Turkmenistan"},
    {country: "Turks and Caicos Islands"},
    {country: "Tuvalu"},
    {country: "U.S. Virgin Islands"},
    {country: "Uganda"},
    {country: "Ukraine"},
    {country: "United Arab Emirates"},
    {country: "United Kingdom"},
    {country: "United States"},
    {country: "Uruguay"},
    {country: "Uzbekistan"},
    {country: "Vanuatu"},
    {country: "Vatican City"},
    {country: "Venezuela"},
    {country: "Vietnam"},
    {country: "Virgin Islands, British"},
    {country: "Wallis and Futuna"},
    {country: "West Bank"},
    {country: "Yemen"},
    {country: "Zambia"},
    {country: "Zimbabwe"},

]