// cities.ts
export const cities = [

    { name: 'Alameda', country: 'USA' },
    { name: 'Albuquerque', country: 'USA' },
    { name: 'Alexandria', country: 'USA' },
    { name: 'Anchorage', country: 'USA' },
    { name: 'Ann Arbor', country: 'USA' },
    { name: 'Arlington', country: 'USA' },
    { name: 'Atlanta', country: 'USA' },
    { name: 'Aurora', country: 'USA' },
    { name: 'Austin', country: 'USA' },
    { name: 'Bakersfield', country: 'USA' },
    { name: 'Baltimore', country: 'USA' },
    { name: 'Baton Rouge', country: 'USA' },
    { name: 'Bellflower', country: 'USA' },
    { name: 'Bellevue', country: 'USA' },
    { name: 'Berkeley', country: 'USA' },
    { name: 'Boise', country: 'USA' },
    { name: 'Boston', country: 'USA' },
    { name: 'Buffalo', country: 'USA' },
    { name: 'Burbank', country: 'USA' },
    { name: 'Cambridge', country: 'USA' },
    { name: 'Chandler', country: 'USA' },
    { name: 'Charlotte', country: 'USA' },
    { name: 'Chesapeake', country: 'USA' },
    { name: 'Chicago', country: 'USA' },
    { name: 'Chula Vista', country: 'USA' },
    { name: 'Cincinnati', country: 'USA' },
    { name: 'Cleveland', country: 'USA' },
    { name: 'Colorado Springs', country: 'USA' },
    { name: 'Columbus', country: 'USA' },
    { name: 'Corona', country: 'USA' },
    { name: 'Corpus Christi', country: 'USA' },
    { name: 'Costa Mesa', country: 'USA' },
    { name: 'Dallas', country: 'USA' },
    { name: 'Dayton', country: 'USA' },
    { name: 'Denton', country: 'USA' },
    { name: 'Denver', country: 'USA' },
    { name: 'Des Moines', country: 'USA' },
    { name: 'Detroit', country: 'USA' },
    { name: 'Durham', country: 'USA' },
    { name: 'El Paso', country: 'USA' },
    { name: 'Elk Grove', country: 'USA' },
    { name: 'Escondido', country: 'USA' },
    { name: 'Eugene', country: 'USA' },
    { name: 'Fairfield', country: 'USA' },
    { name: 'Fayetteville', country: 'USA' },
    { name: 'Fontana', country: 'USA' },
    { name: 'Fort Collins', country: 'USA' },
    { name: 'Fort Lauderdale', country: 'USA' },
    { name: 'Fort Wayne', country: 'USA' },
    { name: 'Fort Worth', country: 'USA' },
    { name: 'Fremont', country: 'USA' },
    { name: 'Fresno', country: 'USA' },
    { name: 'Fullerton', country: 'USA' },
    { name: 'Garland', country: 'USA' },
    { name: 'Gilbert', country: 'USA' },
    { name: 'Glendale', country: 'USA' },
    { name: 'Grand Prairie', country: 'USA' },
    { name: 'Grand Rapids', country: 'USA' },
    { name: 'Green Bay', country: 'USA' },
    { name: 'Greensboro', country: 'USA' },
    { name: 'Hampton', country: 'USA' },
    { name: 'Hartford', country: 'USA' },
    { name: 'Hayward', country: 'USA' },
    { name: 'Hialeah', country: 'USA' },
    { name: 'High Point', country: 'USA' },
    { name: 'Hollywood', country: 'USA' },
    { name: 'Honolulu', country: 'USA' },
    { name: 'Houston', country: 'USA' },
    { name: 'Huntington Beach', country: 'USA' },
    { name: 'Indianapolis', country: 'USA' },
    { name: 'Inglewood', country: 'USA' },
    { name: 'Irvine', country: 'USA' },
    { name: 'Irving', country: 'USA' },
    { name: 'Jackson', country: 'USA' },
    { name: 'Jacksonville', country: 'USA' },
    { name: 'Jersey City', country: 'USA' },
    { name: 'Kansas City', country: 'USA' },
    { name: 'Killeen', country: 'USA' },
    { name: 'Lakewood', country: 'USA' },
    { name: 'Lancaster', country: 'USA' },
    { name: 'Lansing', country: 'USA' },
    { name: 'Laredo', country: 'USA' },
    { name: 'Las Vegas', country: 'USA' },
    { name: 'Lexington', country: 'USA' },
    { name: 'Lincoln', country: 'USA' },
    { name: 'Little Rock', country: 'USA' },
    { name: 'Long Beach', country: 'USA' },
    { name: 'Los Angeles', country: 'USA' },
    { name: 'Louisville', country: 'USA' },
    { name: 'Lowell', country: 'USA' },
    { name: 'Madison', country: 'USA' },
    { name: 'Manchester', country: 'USA' },
    { name: 'McAllen', country: 'USA' },
    { name: 'Memphis', country: 'USA' },
    { name: 'Mesa', country: 'USA' },
    { name: 'Mesquite', country: 'USA' },
    { name: 'Miami', country: 'USA' },
    { name: 'Milwaukee', country: 'USA' },
    { name: 'Minneapolis', country: 'USA' },
    { name: 'Mobile', country: 'USA' },
    { name: 'Modesto', country: 'USA' },
    { name: 'Montgomery', country: 'USA' },
    { name: 'Moreno Valley', country: 'USA' },
    { name: 'Naperville', country: 'USA' },
    { name: 'Nashville', country: 'USA' },
    { name: 'New Haven', country: 'USA' },
    { name: 'New Orleans', country: 'USA' },
    { name: 'New York', country: 'USA' },
    { name: 'Newark', country: 'USA' },
    { name: 'Newport News', country: 'USA' },
    { name: 'Norfolk', country: 'USA' },
    { name: 'Norman', country: 'USA' },
    { name: 'North Las Vegas', country: 'USA' },
    { name: 'Norwalk', country: 'USA' },
    { name: 'Oakland', country: 'USA' },
    { name: 'Oceanside', country: 'USA' },
    { name: 'Oklahoma City', country: 'USA' },
    { name: 'Omaha', country: 'USA' },
    { name: 'Ontario', country: 'USA' },
    { name: 'Orange', country: 'USA' },
    { name: 'Orlando', country: 'USA' },
    { name: 'Overland Park', country: 'USA' },
    { name: 'Oxnard', country: 'USA' },
    { name: 'Palmdale', country: 'USA' },
    { name: 'Pasadena', country: 'USA' },
    { name: 'Paterson', country: 'USA' },
    { name: 'Pembroke Pines', country: 'USA' },
    { name: 'Peoria', country: 'USA' },
    { name: 'Philadelphia', country: 'USA' },
    { name: 'Phoenix', country: 'USA' },
    { name: 'Pittsburgh', country: 'USA' },
    { name: 'Plano', country: 'USA' },
    { name: 'Pomona', country: 'USA' },
    { name: 'Portland', country: 'USA' },
    { name: 'Providence', country: 'USA' },
    { name: 'Provo', country: 'USA' },
    { name: 'Raleigh', country: 'USA' },
    { name: 'Rancho Cucamonga', country: 'USA' },
    { name: 'Reno', country: 'USA' },
    { name: 'Richmond', country: 'USA' },
    { name: 'Riverside', country: 'USA' },
    { name: 'Rochester', country: 'USA' },
    { name: 'Rockford', country: 'USA' },
    { name: 'Roseville', country: 'USA' },
    { name: 'Round Rock', country: 'USA' },
    { name: 'Sacramento', country: 'USA' },
    { name: 'Salem', country: 'USA' },
    { name: 'Salinas', country: 'USA' },
    { name: 'Salt Lake City', country: 'USA' },
    { name: 'San Antonio', country: 'USA' },
    { name: 'San Bernardino', country: 'USA' },
    { name: 'San Diego', country: 'USA' },
    { name: 'San Francisco', country: 'USA' },
    { name: 'San Jose', country: 'USA' },
    { name: 'Santa Ana', country: 'USA' },
    { name: 'Santa Clara', country: 'USA' },
    { name: 'Santa Clarita', country: 'USA' },
    { name: 'Santa Rosa', country: 'USA' },
    { name: 'Savannah', country: 'USA' },
    { name: 'Scottsdale', country: 'USA' },
    { name: 'Seattle', country: 'USA' },
    { name: 'Shreveport', country: 'USA' },
    { name: 'Simi Valley', country: 'USA' },
    { name: 'Sioux Falls', country: 'USA' },
    { name: 'South Bend', country: 'USA' },
    { name: 'Spokane', country: 'USA' },
    { name: 'Springfield', country: 'USA' },
    { name: 'St. Louis', country: 'USA' },
    { name: 'St. Paul', country: 'USA' },
    { name: 'St. Petersburg', country: 'USA' },
    { name: 'Stamford', country: 'USA' },
    { name: 'Sterling Heights', country: 'USA' },
    { name: 'Stockton', country: 'USA' },
    { name: 'Sunnyvale', country: 'USA' },
    { name: 'Surprise', country: 'USA' },
    { name: 'Syracuse', country: 'USA' },
    { name: 'Tacoma', country: 'USA' },
    { name: 'Tallahassee', country: 'USA' },
    { name: 'Tampa', country: 'USA' },
    { name: 'Tempe', country: 'USA' },
    { name: 'Thornton', country: 'USA' },
    { name: 'Thousand Oaks', country: 'USA' },
    { name: 'Toledo', country: 'USA' },
    { name: 'Topeka', country: 'USA' },
    { name: 'Torrance', country: 'USA' },
    { name: 'Tucson', country: 'USA' },
    { name: 'Tulsa', country: 'USA' },
    { name: 'Vallejo', country: 'USA' },
    { name: 'Vancouver', country: 'USA' },
    { name: 'Ventura', country: 'USA' },
    { name: 'Victorville', country: 'USA' },
    { name: 'Virginia Beach', country: 'USA' },
    { name: 'Visalia', country: 'USA' },
    { name: 'Waco', country: 'USA' },
    { name: 'Warren', country: 'USA' },
    { name: 'Washington', country: 'USA' },
    { name: 'Waterbury', country: 'USA' },
    { name: 'West Covina', country: 'USA' },
    { name: 'West Jordan', country: 'USA' },
    { name: 'Westminster', country: 'USA' },
    { name: 'Wichita', country: 'USA' },
    { name: 'Wichita Falls', country: 'USA' },
    { name: 'Wilmington', country: 'USA' },
    { name: 'Winston-Salem', country: 'USA' },
    { name: 'Worcester', country: 'USA' },
    { name: 'Yonkers', country: 'USA' },
    { name: 'Abbotsford', country: 'UK' },
    { name: 'Aberdeen', country: 'UK' },
    { name: 'Armagh', country: 'UK' },
    { name: 'Bangor', country: 'UK' },
    { name: 'Bath', country: 'UK' },
    { name: 'Belfast', country: 'UK' },
    { name: 'Birmingham', country: 'UK' },
    { name: 'Bradford', country: 'UK' },
    { name: 'Brighton', country: 'UK' },
    { name: 'Bristol', country: 'UK' },
    { name: 'Cambridge', country: 'UK' },
    { name: 'Canterbury', country: 'UK' },
    { name: 'Cardiff', country: 'UK' },
    { name: 'Carlisle', country: 'UK' },
    { name: 'Chelmsford', country: 'UK' },
    { name: 'Chester', country: 'UK' },
    { name: 'Chichester', country: 'UK' },
    { name: 'Coventry', country: 'UK' },
    { name: 'Derby', country: 'UK' },
    { name: 'Derry', country: 'UK' },
    { name: 'Dundee', country: 'UK' },
    { name: 'Durham', country: 'UK' },
    { name: 'Edinburgh', country: 'UK' },
    { name: 'Ely', country: 'UK' },
    { name: 'Exeter', country: 'UK' },
    { name: 'Glasgow', country: 'UK' },
    { name: 'Gloucester', country: 'UK' },
    { name: 'Hereford', country: 'UK' },
    { name: 'Inverness', country: 'UK' },
    { name: 'Kingston upon Hull', country: 'UK' },
    { name: 'Lancaster', country: 'UK' },
    { name: 'Leeds', country: 'UK' },
    { name: 'Leicester', country: 'UK' },
    { name: 'Lichfield', country: 'UK' },
    { name: 'Lincoln', country: 'UK' },
    { name: 'Liverpool', country: 'UK' },
    { name: 'City of London', country: 'UK' },
    { name: 'Manchester', country: 'UK' },
    { name: 'Newcastle upon Tyne', country: 'UK' },
    { name: 'Newport', country: 'UK' },
    { name: 'Newry', country: 'UK' },
    { name: 'Norwich', country: 'UK' },
    { name: 'Nottingham', country: 'UK' },
    { name: 'Oxford', country: 'UK' },
    { name: 'Perth', country: 'UK' },
    { name: 'Peterborough', country: 'UK' },
    { name: 'Plymouth', country: 'UK' },
    { name: 'Portsmouth', country: 'UK' },
    { name: 'Preston', country: 'UK' },
    { name: 'Ripon', country: 'UK' },
    { name: 'St Albans', country: 'UK' },
    { name: 'St Asaph', country: 'UK' },
    { name: 'St David\'s', country: 'UK' },
    { name: 'Stirling', country: 'UK' },
    { name: 'Stoke-on-Trent', country: 'UK' },
    { name: 'Sunderland', country: 'UK' },
    { name: 'Swansea', country: 'UK' },
    { name: 'Truro', country: 'UK' },
    { name: 'Wakefield', country: 'UK' },
    { name: 'Wells', country: 'UK' },
    { name: 'Westminster', country: 'UK' },
    { name: 'Winchester', country: 'UK' },
    { name: 'Wolverhampton', country: 'UK' },
    { name: 'Worcester', country: 'UK' },
    { name: 'York', country: 'UK' },
    { name: 'Cairo', country: 'Egypt' },
    { name: 'Giza', country: 'Egypt' },
    { name: 'Alexandria', country: 'Egypt' },
    { name: 'Luxor', country: 'Egypt' },
    { name: 'Aswan', country: 'Egypt' },
    { name: 'Sharm el-Sheikh', country: 'Egypt' },
    { name: 'Hurghada', country: 'Egypt' },
    { name: 'Marsa Alam', country: 'Egypt' },
    { name: 'Suez', country: 'Egypt' },
    { name: 'Ismailia', country: 'Egypt' },
    { name: 'Port Said', country: 'Egypt' },
    { name: 'El Mahalla El Kubra', country: 'Egypt' },
    { name: 'Damietta', country: 'Egypt' },
    { name: 'Kafr El Sheikh', country: 'Egypt' },
    { name: 'Asyut', country: 'Egypt' },
    { name: 'Beni Suef', country: 'Egypt' },
    { name: 'Faiyum', country: 'Egypt' },
    { name: 'Minya', country: 'Egypt' },
    { name: 'Sohag', country: 'Egypt' },
    { name: 'Qena', country: 'Egypt' },
    { name: 'Aswan', country: 'Egypt' },
    { name: 'Luxor', country: 'Egypt' },
    { name: 'Giza', country: 'Egypt' },
    { name: 'Sharm el-Sheikh', country: 'Egypt' },
    { name: 'Hurghada', country: 'Egypt' },
    { name: 'Mansoura', country: 'Egypt' },
    { name: 'Zagazig', country: 'Egypt' },
    { name: 'Tanta', country: 'Egypt' },
    { name: 'Akhmim', country: 'Egypt' },
    { name: 'Kisumu', country: 'Kenya' },
    { name: 'Nairobi', country: 'Kenya' },
    { name: 'Mombasa', country: 'Kenya' },
    { name: 'Kisii', country: 'Kenya' },
    { name: 'Nakuru', country: 'Kenya' },
    { name: 'Eldoret', country: 'Kenya' },
    { name: 'Nyeri', country: 'Kenya' },
    { name: 'Thika', country: 'Kenya' },
    { name: 'Kakamega', country: 'Kenya' },
    { name: 'Malindi', country: 'Kenya' },
    { name: 'Kitale', country: 'Kenya' },
    { name: 'Naivasha', country: 'Kenya' },
    { name: 'Garissa', country: 'Kenya' },
    { name: 'Meru', country: 'Kenya' },
    { name: 'Wajir', country: 'Kenya' },
    { name: 'Nyahururu', country: 'Kenya' },
    { name: 'Embu', country: 'Kenya' },
    { name: 'Kericho', country: 'Kenya' },
    { name: 'Isiolo', country: 'Kenya' },
    { name: 'Mandera', country: 'Kenya' },
    { name: 'Kilifi', country: 'Kenya' },
    { name: 'Bomet', country: 'Kenya' },
    { name: 'Voi', country: 'Kenya' },
    { name: 'Homa Bay', country: 'Kenya' },
    { name: 'Lamu', country: 'Kenya' },
    { name: 'Wote', country: 'Kenya' },
    { name: 'Hola', country: 'Kenya' },
    { name: 'Lodwar', country: 'Kenya' },
    { name: 'Turkana', country: 'Kenya' },
    { name: 'Kabarnet', country: 'Kenya' },
    { name: 'Makueni', country: 'Kenya' },
    { name: 'Narok', country: 'Kenya' },
    { name: 'Kajiado', country: 'Kenya' },
    { name: 'Busia', country: 'Kenya' },
    { name: 'Siaya', country: 'Kenya' },
    { name: 'Nandi', country: 'Kenya' },
    { name: 'Migori', country: 'Kenya' },
    { name: 'Bungoma', country: 'Kenya' },
    { name: 'Marsabit', country: 'Kenya' },
    { name: 'Taita Taveta', country: 'Kenya' },
    { name: 'Laikipia', country: 'Kenya' },
    { name: 'Nyamira', country: 'Kenya' },
    { name: 'Samburu', country: 'Kenya' },
    { name: 'Tana River', country: 'Kenya' },
    { name: 'Tharaka Nithi', country: 'Kenya' },
    { name: 'Elgeyo Marakwet', country: 'Kenya' },
    { name: 'Trans Nzoia', country: 'Kenya' },
    { name: 'West Pokot', country: 'Kenya' },
    { name: 'Nairobi', country: 'Kenya' },
    { name: 'Mombasa', country: 'Kenya' },
    { name: 'Kisumu', country: 'Kenya' },
    { name: 'Nakuru', country: 'Kenya' },
    { name: 'Eldoret', country: 'Kenya' },
    { name: 'Malindi', country: 'Kenya' },
    { name: 'Kitale', country: 'Kenya' },
    { name: 'Garissa', country: 'Kenya' },
    { name: 'Kakamega', country: 'Kenya' },
    { name: 'Bungoma', country: 'Kenya' },
    { name: 'Busia', country: 'Kenya' },
    { name: 'Nyeri', country: 'Kenya' },
    { name: 'Machakos', country: 'Kenya' },
    { name: 'Kiambu', country: 'Kenya' },
    { name: 'Lamu', country: 'Kenya' },
    { name: 'Kericho', country: 'Kenya' },
    { name: 'Bomet', country: 'Kenya' },
    { name: 'Marsabit', country: 'Kenya' },
    { name: 'Kajiado', country: 'Kenya' },
    { name: 'Isiolo', country: 'Kenya' },
    { name: 'Wajir', country: 'Kenya' },
    { name: 'Mandera', country: 'Kenya' },
    { name: 'Migori', country: 'Kenya' },
    { name: 'Homa Bay', country: 'Kenya' },
    { name: 'Turkana', country: 'Kenya' },
    { name: 'Tana River', country: 'Kenya' },
    { name: 'Lodwar', country: 'Kenya' },
    { name: 'Makueni', country: 'Kenya' },
    { name: 'Samburu', country: 'Kenya' },
    { name: 'Nyandarua', country: 'Kenya' },
    { name: 'Nyamira', country: 'Kenya' },
    { name: 'Kilifi', country: 'Kenya' },
    { name: 'Taita Taveta', country: 'Kenya' },
    { name: 'Tharaka Nithi', country: 'Kenya' },
    { name: 'Nandi', country: 'Kenya' },
    { name: 'Trans Nzoia', country: 'Kenya' },
    { name: 'Elgeyo Marakwet', country: 'Kenya' },
    { name: 'West Pokot', country: 'Kenya' },
    { name: 'Turkana', country: 'Kenya' },
    { name: 'Tana River', country: 'Kenya' },
    { name: 'Lodwar', country: 'Kenya' },
    { name: 'Makueni', country: 'Kenya' },
    { name: 'Samburu', country: 'Kenya' },
    { name: 'Nyandarua', country: 'Kenya' },
    { name: 'Nyamira', country: 'Kenya' },
    { name: 'Kilifi', country: 'Kenya' },
    { name: 'Taita Taveta', country: 'Kenya' },
    { name: 'Tharaka Nithi', country: 'Kenya' },
    { name: 'Nandi', country: 'Kenya' },
    { name: 'Trans Nzoia', country: 'Kenya' },
    { name: 'Elgeyo Marakwet', country: 'Kenya' },
    { name: 'West Pokot', country: 'Kenya' },
    { name: 'Turkana', country: 'Kenya' },
    { name: 'Tana River', country: 'Kenya' },
    { name: 'Lodwar', country: 'Kenya' },
    { name: 'Makueni', country: 'Kenya' },
    { name: 'Samburu', country: 'Kenya' },
    { name: 'Nyandarua', country: 'Kenya' },
    { name: 'Nyamira', country: 'Kenya' },
    { name: 'Kilifi', country: 'Kenya' },
    { name: 'Taita Taveta', country: 'Kenya' },
    { name: 'Tharaka Nithi', country: 'Kenya' },
    { name: 'Nandi', country: 'Kenya' },
    { name: 'Trans Nzoia', country: 'Kenya' },
    { name: 'Elgeyo Marakwet', country: 'Kenya' },
    { name: 'West Pokot', country: 'Kenya' },
    { name: 'Nairobi', country: 'Kenya' },
    { name: 'Mombasa', country: 'Kenya' },
    { name: 'Kisumu', country: 'Kenya' },
    { name: 'Nakuru', country: 'Kenya' },
    { name: 'Eldoret', country: 'Kenya' },
    { name: 'Malindi', country: 'Kenya' },
    { name: 'Kitale', country: 'Kenya' },
    { name: 'Garissa', country: 'Kenya' },
    { name: 'Kakamega', country: 'Kenya' },
    { name: 'Bungoma', country: 'Kenya' },
    { name: 'Busia', country: 'Kenya' },
    { name: 'Nyeri', country: 'Kenya' },
    { name: 'Machakos', country: 'Kenya' },
    { name: 'Kiambu', country: 'Kenya' },
    { name: 'Lamu', country: 'Kenya' },
    { name: 'Kericho', country: 'Kenya' },
    { name: 'Bomet', country: 'Kenya' },
    { name: 'Marsabit', country: 'Kenya' },
    { name: 'Kajiado', country: 'Kenya' },
    { name: 'Isiolo', country: 'Kenya' },
    { name: 'Wajir', country: 'Kenya' },
    { name: 'Mandera', country: 'Kenya' },
    { name: 'Migori', country: 'Kenya' },
    { name: 'Homa Bay', country: 'Kenya' },
    { name: 'Turkana', country: 'Kenya' },
    { name: 'Tana River', country: 'Kenya' },
    { name: 'Lodwar', country: 'Kenya' },
    { name: 'Makueni', country: 'Kenya' },
    { name: 'Samburu', country: 'Kenya' },
    { name: 'Nyandarua', country: 'Kenya' },
    { name: 'Nyamira', country: 'Kenya' },
    { name: 'Kilifi', country: 'Kenya' },
    { name: 'Taita Taveta', country: 'Kenya' },
    { name: 'Tharaka Nithi', country: 'Kenya' },
    { name: 'Nandi', country: 'Kenya' },
    { name: 'Trans Nzoia', country: 'Kenya' },
    { name: 'Elgeyo Marakwet', country: 'Kenya' },
    { name: 'West Pokot', country: 'Kenya' },
    { name: 'Turkana', country: 'Kenya' },
    { name: 'Tana River', country: 'Kenya' },
    { name: 'Lodwar', country: 'Kenya' },
    { name: 'Makueni', country: 'Kenya' },
    { name: 'Samburu', country: 'Kenya' },
    { name: 'Nyandarua', country: 'Kenya' },
    { name: 'Nyamira', country: 'Kenya' },
    { name: 'Kilifi', country: 'Kenya' },
    { name: 'Taita Taveta', country: 'Kenya' },
    { name: 'Tharaka Nithi', country: 'Kenya' },
    { name: 'Nandi', country: 'Kenya' },
    { name: 'Trans Nzoia', country: 'Kenya' },
    { name: 'Elgeyo Marakwet', country: 'Kenya' },
    { name: 'West Pokot', country: 'Kenya' },
    { name: 'Addis Ababa', country: 'Ethiopia' },
    { name: 'Dire Dawa', country: 'Ethiopia' },
    { name: 'Mekelle', country: 'Ethiopia' },
    { name: 'Gondar', country: 'Ethiopia' },
    { name: 'Bahir Dar', country: 'Ethiopia' },
    { name: 'Hawassa', country: 'Ethiopia' },
    { name: 'Jimma', country: 'Ethiopia' },
    { name: 'Jijiga', country: 'Ethiopia' },
    { name: 'Shashamane', country: 'Ethiopia' },
    { name: 'Desse', country: 'Ethiopia' },
    { name: 'Sodo', country: 'Ethiopia' },
    { name: 'Debre Birhan', country: 'Ethiopia' },
    { name: 'Debre Zeyit', country: 'Ethiopia' },
    { name: 'Semera', country: 'Ethiopia' },
    { name: 'Harar', country: 'Ethiopia' },
    { name: 'Nazret', country: 'Ethiopia' },
    { name: 'Nekemte', country: 'Ethiopia' },
    { name: 'Asella', country: 'Ethiopia' },
    { name: 'Gambela', country: 'Ethiopia' },
    { name: 'Giyon', country: 'Ethiopia' },
    { name: 'Dila', country: 'Ethiopia' },
    { name: 'Hosaena', country: 'Ethiopia' },
    { name: 'Bahir Dar', country: 'Ethiopia' },
    { name: 'Hawassa', country: 'Ethiopia' },
    { name: 'Jimma', country: 'Ethiopia' },
    { name: 'Jijiga', country: 'Ethiopia' },
    { name: 'Shashamane', country: 'Ethiopia' },
    { name: 'Desse', country: 'Ethiopia' },
    { name: 'Sodo', country: 'Ethiopia' },
    { name: 'Debre Birhan', country: 'Ethiopia' },
    { name: 'Debre Zeyit', country: 'Ethiopia' },
    { name: 'Semera', country: 'Ethiopia' },
    { name: 'Harar', country: 'Ethiopia' },
    { name: 'Nazret', country: 'Ethiopia' },
    { name: 'Nekemte', country: 'Ethiopia' },
    { name: 'Asella', country: 'Ethiopia' },
    { name: 'Gambela', country: 'Ethiopia' },
    { name: 'Giyon', country: 'Ethiopia' },
    { name: 'Dila', country: 'Ethiopia' },
    { name: 'Hosaena', country: 'Ethiopia' },
    { name: 'Juba', country: 'South Sudan' },
    { name: 'Wau', country: 'South Sudan' },
    { name: 'Malakal', country: 'South Sudan' },
    { name: 'Rumbek', country: 'South Sudan' },
    { name: 'Bor', country: 'South Sudan' },
    { name: 'Aweil', country: 'South Sudan' },
    { name: 'Pibor', country: 'South Sudan' },
    { name: 'Yei', country: 'South Sudan' },
    { name: 'Kapoeta', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    { name: 'Torit', country: 'South Sudan' },
    { name: 'Bentiu', country: 'South Sudan' },
    { name: 'Kuajok', country: 'South Sudan' },
    { name: 'Tonj', country: 'South Sudan' },
    { name: 'Raja', country: 'South Sudan' },
    { name: 'Renk', country: 'South Sudan' },
    { name: 'Nasir', country: 'South Sudan' },
    { name: 'Maridi', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    { name: 'Juba', country: 'South Sudan' },
    { name: 'Wau', country: 'South Sudan' },
    { name: 'Malakal', country: 'South Sudan' },
    { name: 'Rumbek', country: 'South Sudan' },
    { name: 'Bor', country: 'South Sudan' },
    { name: 'Aweil', country: 'South Sudan' },
    { name: 'Pibor', country: 'South Sudan' },
    { name: 'Yei', country: 'South Sudan' },
    { name: 'Kapoeta', country: 'South Sudan' },
    { name: 'Torit', country: 'South Sudan' },
    { name: 'Bentiu', country: 'South Sudan' },
    { name: 'Kuajok', country: 'South Sudan' },
    { name: 'Tonj', country: 'South Sudan' },
    { name: 'Raja', country: 'South Sudan' },
    { name: 'Renk', country: 'South Sudan' },
    { name: 'Nasir', country: 'South Sudan' },
    { name: 'Maridi', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    { name: 'Juba', country: 'South Sudan' },
    { name: 'Wau', country: 'South Sudan' },
    { name: 'Malakal', country: 'South Sudan' },
    { name: 'Rumbek', country: 'South Sudan' },
    { name: 'Bor', country: 'South Sudan' },
    { name: 'Aweil', country: 'South Sudan' },
    { name: 'Pibor', country: 'South Sudan' },
    { name: 'Yei', country: 'South Sudan' },
    { name: 'Kapoeta', country: 'South Sudan' },
    { name: 'Torit', country: 'South Sudan' },
    { name: 'Bentiu', country: 'South Sudan' },
    { name: 'Kuajok', country: 'South Sudan' },
    { name: 'Tonj', country: 'South Sudan' },
    { name: 'Raja', country: 'South Sudan' },
    { name: 'Renk', country: 'South Sudan' },
    { name: 'Nasir', country: 'South Sudan' },
    { name: 'Maridi', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    { name: 'Juba', country: 'South Sudan' },
    { name: 'Wau', country: 'South Sudan' },
    { name: 'Malakal', country: 'South Sudan' },
    { name: 'Rumbek', country: 'South Sudan' },
    { name: 'Bor', country: 'South Sudan' },
    { name: 'Aweil', country: 'South Sudan' },
    { name: 'Pibor', country: 'South Sudan' },
    { name: 'Yei', country: 'South Sudan' },
    { name: 'Kapoeta', country: 'South Sudan' },
    { name: 'Torit', country: 'South Sudan' },
    { name: 'Bentiu', country: 'South Sudan' },
    { name: 'Kuajok', country: 'South Sudan' },
    { name: 'Tonj', country: 'South Sudan' },
    { name: 'Raja', country: 'South Sudan' },
    { name: 'Renk', country: 'South Sudan' },
    { name: 'Nasir', country: 'South Sudan' },
    { name: 'Maridi', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    { name: 'Juba', country: 'South Sudan' },
    { name: 'Wau', country: 'South Sudan' },
    { name: 'Malakal', country: 'South Sudan' },
    { name: 'Rumbek', country: 'South Sudan' },
    { name: 'Bor', country: 'South Sudan' },
    { name: 'Aweil', country: 'South Sudan' },
    { name: 'Pibor', country: 'South Sudan' },
    { name: 'Yei', country: 'South Sudan' },
    { name: 'Kapoeta', country: 'South Sudan' },
    { name: 'Torit', country: 'South Sudan' },
    { name: 'Bentiu', country: 'South Sudan' },
    { name: 'Kuajok', country: 'South Sudan' },
    { name: 'Tonj', country: 'South Sudan' },
    { name: 'Raja', country: 'South Sudan' },
    { name: 'Renk', country: 'South Sudan' },
    { name: 'Nasir', country: 'South Sudan' },
    { name: 'Maridi', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    { name: 'Juba', country: 'South Sudan' },
    { name: 'Wau', country: 'South Sudan' },
    { name: 'Malakal', country: 'South Sudan' },
    { name: 'Rumbek', country: 'South Sudan' },
    { name: 'Bor', country: 'South Sudan' },
    { name: 'Aweil', country: 'South Sudan' },
    { name: 'Pibor', country: 'South Sudan' },
    { name: 'Yei', country: 'South Sudan' },
    { name: 'Kapoeta', country: 'South Sudan' },
    { name: 'Torit', country: 'South Sudan' },
    { name: 'Bentiu', country: 'South Sudan' },
    { name: 'Kuajok', country: 'South Sudan' },
    { name: 'Tonj', country: 'South Sudan' },
    { name: 'Raja', country: 'South Sudan' },
    { name: 'Renk', country: 'South Sudan' },
    { name: 'Nasir', country: 'South Sudan' },
    { name: 'Maridi', country: 'South Sudan' },
    { name: 'Yambio', country: 'South Sudan' },
    // Indian Cities

    { name: 'Trivandrum', country: 'India' },
    // Indian Cities
    { name: 'Mumbai', country: 'India' },
    { name: 'Delhi', country: 'India' },
    { name: 'Bangalore', country: 'India' },
    { name: 'Chennai', country: 'India' },
    { name: 'Kolkata', country: 'India' },
    { name: 'Hyderabad', country: 'India' },
    { name: 'Pune', country: 'India' },
    { name: 'Ahmedabad', country: 'India' },
    { name: 'Jaipur', country: 'India' },
    { name: 'Lucknow', country: 'India' },
    { name: 'Kanpur', country: 'India' },
    { name: 'Nagpur', country: 'India' },
    { name: 'Indore', country: 'India' },
    { name: 'Thane', country: 'India' },
    { name: 'Bhopal', country: 'India' },
    { name: 'Visakhapatnam', country: 'India' },
    { name: 'Pimpri-Chinchwad', country: 'India' },
    { name: 'Patna', country: 'India' },
    { name: 'Vadodara', country: 'India' },
    { name: 'Ghaziabad', country: 'India' },
    { name: 'Ludhiana', country: 'India' },
    { name: 'Agra', country: 'India' },
    { name: 'Nashik', country: 'India' },
    { name: 'Faridabad', country: 'India' },
    { name: 'Meerut', country: 'India' },
    { name: 'Rajkot', country: 'India' },
    { name: 'Varanasi', country: 'India' },
    { name: 'Srinagar', country: 'India' },
    { name: 'Aurangabad', country: 'India' },
    { name: 'Dhanbad', country: 'India' },
    { name: 'Amritsar', country: 'India' },
    { name: 'Allahabad', country: 'India' },
    { name: 'Ranchi', country: 'India' },
    { name: 'Howrah', country: 'India' },
    { name: 'Coimbatore', country: 'India' },
    { name: 'Jabalpur', country: 'India' },
    { name: 'Gwalior', country: 'India' },
    { name: 'Vijayawada', country: 'India' },
    { name: 'Jodhpur', country: 'India' },
    { name: 'Madurai', country: 'India' },
    { name: 'Raipur', country: 'India' },
    { name: 'Kota', country: 'India' },
    { name: 'Guwahati', country: 'India' },
    { name: 'Chandigarh', country: 'India' },
    { name: 'Solapur', country: 'India' },
    { name: 'Hubli–Dharwad', country: 'India' },
    { name: 'Bareilly', country: 'India' },
    { name: 'Moradabad', country: 'India' },
    { name: 'Mysore', country: 'India' },
    { name: 'Gurgaon', country: 'India' },
    { name: 'Aligarh', country: 'India' },
    { name: 'Jalandhar', country: 'India' },
    { name: 'Tiruchirappalli', country: 'India' },
    { name: 'Bhubaneswar', country: 'India' },
    { name: 'Salem', country: 'India' },
    { name: 'Mira-Bhayandar', country: 'India' },
    { name: 'Warangal', country: 'India' },
    { name: 'Thiruvananthapuram', country: 'India' },
    { name: 'Guntur', country: 'India' },
    { name: 'Bhiwandi', country: 'India' },
    { name: 'Saharanpur', country: 'India' },
    { name: 'Gorakhpur', country: 'India' },
    { name: 'Bikaner', country: 'India' },
    { name: 'Amravati', country: 'India' },
    { name: 'Noida', country: 'India' },
    { name: 'Jamshedpur', country: 'India' },
    { name: 'Bhilai', country: 'India' },
    { name: 'Cuttack', country: 'India' },
    { name: 'Firozabad', country: 'India' },
    { name: 'Kochi', country: 'India' },
    { name: 'Nellore', country: 'India' },
    { name: 'Bhavnagar', country: 'India' },
    { name: 'Dehradun', country: 'India' },
    { name: 'Durgapur', country: 'India' },
    { name: 'Asansol', country: 'India' },
    { name: 'Rourkela', country: 'India' },
    { name: 'Nanded', country: 'India' },
    { name: 'Kolhapur', country: 'India' },
    { name: 'Ajmer', country: 'India' },
    { name: 'Akola', country: 'India' },
    { name: 'Gulbarga', country: 'India' },
    { name: 'Jamnagar', country: 'India' },
    { name: 'Ujjain', country: 'India' },
    { name: 'Loni', country: 'India' },
    { name: 'Siliguri', country: 'India' },
    { name: 'Jhansi', country: 'India' },
    { name: 'Ulhasnagar', country: 'India' },
    { name: 'Jammu', country: 'India' },
    { name: 'Sangli-Miraj & Kupwad', country: 'India' },
    { name: 'Mangalore', country: 'India' },
    { name: 'Erode', country: 'India' },
    { name: 'Belgaum', country: 'India' },
    { name: 'Ambattur', country: 'India' },
    { name: 'Tirunelveli', country: 'India' },
    { name: 'Malegaon', country: 'India' },
    { name: 'Gaya', country: 'India' },
    { name: 'Jalgaon', country: 'India' },
    { name: 'Udaipur', country: 'India' },
    { name: 'Maheshtala', country: 'India' },
    { name: 'Davanagere', country: 'India' },
    { name: 'Kozhikode', country: 'India' },
    { name: 'Kurnool', country: 'India' },
    { name: 'Rajpur Sonarpur', country: 'India' },
    { name: 'Rajahmundry', country: 'India' },
    { name: 'Bokaro Steel City', country: 'India' },
    { name: 'South Dumdum', country: 'India' },
    { name: 'Bellary', country: 'India' },
    { name: 'Patiala', country: 'India' },
    { name: 'Gopalpur', country: 'India' },
    { name: 'Agartala', country: 'India' },
    { name: 'Bhagalpur', country: 'India' },
    { name: 'Muzaffarnagar', country: 'India' },
    { name: 'Bhatpara', country: 'India' },
    { name: 'Panihati', country: 'India' },
    { name: 'Latur', country: 'India' },
    { name: 'Dhule', country: 'India' },
    { name: 'Rohtak', country: 'India' },
    { name: 'Korba', country: 'India' },
    { name: 'Bhilwara', country: 'India' },
    { name: 'Berhampur', country: 'India' },
    { name: 'Muzaffarpur', country: 'India' },
    { name: 'Ahmednagar', country: 'India' },
    { name: 'Mathura', country: 'India' },
    { name: 'Kollam', country: 'India' },
    { name: 'Avadi', country: 'India' },
    { name: 'Kadapa', country: 'India' },
    { name: 'Anantapur', country: 'India' },
    { name: 'Kamarhati', country: 'India' },
    { name: 'Bilaspur', country: 'India' },
    { name: 'Shahjahanpur', country: 'India' },
    { name: 'Satara', country: 'India' },
    { name: 'Bijapur', country: 'India' },
    { name: 'Kakinada', country: 'India' },
    { name: 'Rampur', country: 'India' },
    { name: 'Shivamogga', country: 'India' },
    { name: 'Chandrapur', country: 'India' },
    { name: 'Junagadh', country: 'India' },
    { name: 'Thrissur', country: 'India' },
    { name: 'Alwar', country: 'India' },
    { name: 'Bardhaman', country: 'India' },
    { name: 'Kulti', country: 'India' },
    { name: 'Nizamabad', country: 'India' },
    { name: 'Parbhani', country: 'India' },
    { name: 'Tumkur', country: 'India' },
    { name: 'Khammam', country: 'India' },
    { name: 'Ozhukarai', country: 'India' },
    { name: 'Bihar Sharif', country: 'India' },
    { name: 'Panipat', country: 'India' },
    { name: 'Darbhanga', country: 'India' },
    { name: 'Bally', country: 'India' },
    { name: 'Aizawl', country: 'India' },
    { name: 'Ichalkaranji', country: 'India' },
    { name: 'Dewas', country: 'India' },
    { name: 'Karnal', country: 'India' },
    { name: 'Bathinda', country: 'India' },
    { name: 'Jalna', country: 'India' },
    { name: 'Eluru', country: 'India' },
    { name: 'Barasat', country: 'India' },
    { name: 'Kirari Suleman Nagar', country: 'India' },
    { name: 'Purnia', country: 'India' },
    { name: 'Satna', country: 'India' },
    { name: 'Mau', country: 'India' },
    { name: 'Sonipat', country: 'India' },
    { name: 'Farrukhabad', country: 'India' },
    { name: 'Sagar', country: 'India' },
    { name: 'Rourkela', country: 'India' },
    { name: 'Durg', country: 'India' },
    { name: 'Imphal', country: 'India' },
    { name: 'Ratlam', country: 'India' },
    { name: 'Hapur', country: 'India' },
    { name: 'Arrah', country: 'India' },
    { name: 'Karimnagar', country: 'India' },
    { name: 'Anantapur', country: 'India' },
    { name: 'Etawah', country: 'India' },
    { name: 'Ambarnath', country: 'India' },
    { name: 'North Dumdum', country: 'India' },
    { name: 'Bharatpur', country: 'India' },
    { name: 'Begusarai', country: 'India' },
    { name: 'New Delhi', country: 'India' },
    { name: 'Gandhidham', country: 'India' },
    { name: 'Baranagar', country: 'India' },
    { name: 'Tiruvottiyur', country: 'India' },
    { name: 'Pondicherry', country: 'India' },
    { name: 'Sikar', country: 'India' },
    { name: 'Thoothukudi', country: 'India' },
    { name: 'Rewa', country: 'India' },
    { name: 'Mirzapur', country: 'India' },
    { name: 'Raichur', country: 'India' },
    { name: 'Pali', country: 'India' },
    { name: 'Ramagundam', country: 'India' },
    { name: 'Silchar', country: 'India' },
    { name: 'Haridwar', country: 'India' },
    { name: 'Vijayanagaram', country: 'India' },
    { name: 'Tenali', country: 'India' },
    { name: 'Nagercoil', country: 'India' },
    { name: 'Sri Ganganagar', country: 'India' },
    { name: 'Karawal Nagar', country: 'India' },
    { name: 'Mango', country: 'India' },
    { name: 'Thanjavur', country: 'India' },
    { name: 'Bulandshahr', country: 'India' },
    { name: 'Uluberia', country: 'India' },
    { name: 'Katni', country: 'India' },
    { name: 'Sambhal', country: 'India' },
    { name: 'Singrauli', country: 'India' },
    { name: 'Nadiad', country: 'India' },
    { name: 'Secunderabad', country: 'India' },
    { name: 'Naihati', country: 'India' },
    { name: 'Yamunanagar', country: 'India' },
    { name: 'Bidar', country: 'India' },
    { name: 'Pallavaram', country: 'India' },
    { name: 'Bidhan Nagar', country: 'India' },
    { name: 'Kharagpur', country: 'India' },
    { name: 'Dindigul', country: 'India' },
    { name: 'Junagadh', country: 'India' },
    { name: 'Hospet', country: 'India' },
    { name: 'Khammam', country: 'India' },
    { name: 'Sangli', country: 'India' },
    { name: 'Chhattarpur', country: 'India' },
    { name: 'Raiganj', country: 'India' },
    { name: 'Sirsa', country: 'India' },
    { name: 'Karimnagar', country: 'India' },
    { name: 'Sultan Pur Majra', country: 'India' },
    { name: 'Hajipur', country: 'India' },
    { name: 'Bhind', country: 'India' },
    { name: 'Mahbubnagar', country: 'India' },
    { name: 'Port Blair', country: 'India' },
    { name: 'Jorhat', country: 'India' },
    { name: 'Hazaribagh', country: 'India' },
    { name: 'Haldia', country: 'India' },
    { name: 'Katihar', country: 'India' },
    { name: 'Vellore', country: 'India' },
    { name: 'Alappuzha', country: 'India' },
    { name: 'Kottayam', country: 'India' },
    { name: 'Machilipatnam', country: 'India' },
    { name: 'Shimla', country: 'India' },
    { name: 'Adoni', country: 'India' },
    { name: 'Munger', country: 'India' },
    { name: 'Kanchipuram', country: 'India' },
    { name: 'Dibrugarh', country: 'India' },
    { name: 'Godhra', country: 'India' },
    { name: 'Hajipur', country: 'India' },
    { name: 'Suryapet', country: 'India' },
    { name: 'Hindupur', country: 'India' },
    { name: 'Nagaon', country: 'India' },
    { name: 'Hoshiarpur', country: 'India' },
    { name: 'Narasaraopet', country: 'India' },
    { name: 'Dehri', country: 'India' },
    { name: 'Panvel', country: 'India' },
    { name: 'Barasat', country: 'India' },
    { name: 'Guna', country: 'India' },
    { name: 'Khambhat', country: 'India' },
    { name: 'Chandausi', country: 'India' },
    { name: 'Ongole', country: 'India' },
    { name: 'Bettiah', country: 'India' },
    { name: 'Porbandar', country: 'India' },
    { name: 'Palani', country: 'India' },
    { name: 'Anand', country: 'India' },
    { name: 'Puri', country: 'India' },
    { name: 'Jehanabad', country: 'India' },
    { name: 'Bargarh', country: 'India' },
    { name: 'Anantnag', country: 'India' },
    { name: 'Nandurbar', country: 'India' },
    { name: 'Chhapra', country: 'India' },
    { name: 'Bhuj', country: 'India' },
    { name: 'Khandwa', country: 'India' },
    { name: 'Yavatmal', country: 'India' },
    { name: 'Kolar', country: 'India' },
    { name: 'Kumbakonam', country: 'India' },
    { name: 'Sambalpur', country: 'India' },
    { name: 'Shahjahanpur', country: 'India' },
    { name: 'Bilaspur', country: 'India' },
    { name: 'Karad', country: 'India' },
    { name: 'Shivpuri', country: 'India' },
    { name: 'Surendranagar', country: 'India' },
    { name: 'Salem', country: 'India' },
    { name: 'Madhyamgram', country: 'India' },
    { name: 'Bathinda', country: 'India' },
    { name: 'Haldwani', country: 'India' },
    { name: 'Gangtok', country: 'India' },
    { name: 'Bhimavaram', country: 'India' },
    { name: 'Chittoor', country: 'India' },
    { name: 'Kumbakonam', country: 'India' },
    { name: 'Raniganj', country: 'India' },
    { name: 'Hosur', country: 'India' },
    { name: 'Bhind', country: 'India' },
    { name: 'Berhampore', country: 'India' },
    { name: 'Dharmavaram', country: 'India' },
    { name: 'Raigarh', country: 'India' },
    { name: 'Hassan', country: 'India' },
    { name: 'Bagaha', country: 'India' },
    { name: 'Namakkal', country: 'India' },
    { name: 'Nagaon', country: 'India' },
    { name: 'Godhra', country: 'India' },
    { name: 'Mahbubnagar', country: 'India' },
    { name: 'Mahesana', country: 'India' },
    { name: 'Srikakulam', country: 'India' },
    { name: 'Tonk', country: 'India' },
    { name: 'Sirsa', country: 'India' },
    { name: 'Jaunpur', country: 'India' },
    { name: 'Madanapalle', country: 'India' },
    { name: 'Hindupur', country: 'India' },
    { name: 'Nagapattinam', country: 'India' },
    { name: 'Unnao', country: 'India' },
    { name: 'Tadepalligudem', country: 'India' },
    { name: 'Karaikudi', country: 'India' },
    { name: 'Morena', country: 'India' },
    { name: 'Hosapete', country: 'India' },
    { name: 'Amroha', country: 'India' },
    { name: 'Jorhat', country: 'India' },
    { name: 'Madhubani', country: 'India' },
    { name: 'Fatehpur', country: 'India' },
    { name: 'Balurghat', country: 'India' },
    { name: 'Chitradurga', country: 'India' },
    { name: 'Ambikapur', country: 'India' },
    { name: 'Bhuj', country: 'India' },
    { name: 'Proddatur', country: 'India' },
    { name: 'Palanpur', country: 'India' },
    { name: 'Wardha', country: 'India' },
    { name: 'Satara', country: 'India' },
    { name: 'Churu', country: 'India' },
    { name: 'Rayachoti', country: 'India' },
    { name: 'Koratla', country: 'India' },
    { name: 'Pithampur', country: 'India' },
    { name: 'Wardha', country: 'India' },
    { name: 'Miryalaguda', country: 'India' },
    { name: 'Kolar', country: 'India' },
    { name: 'Mandya', country: 'India' },
    { name: 'Amalner', country: 'India' },
    { name: 'Nahan', country: 'India' },
    { name: 'Wardha', country: 'India' },
    { name: 'Dharmavaram', country: 'India' },
    { name: 'Khammam', country: 'India' },
    { name: 'Sanawad', country: 'India' },
    { name: 'Nawada', country: 'India' },
    { name: 'Jagtial', country: 'India' },
    { name: 'Vikarabad', country: 'India' },
    { name: 'Narwana', country: 'India' },
    { name: 'Narayanpet', country: 'India' },
    { name: 'Mangalvedhe', country: 'India' },
    { name: 'Jhunjhunun', country: 'India' },
    { name: 'Baleshwar Town', country: 'India' },
    { name: 'Kottayam', country: 'India' },
    { name: 'Cuddapah', country: 'India' },
    { name: 'Debagarh', country: 'India' },
    { name: 'Bhadrak', country: 'India' },
    { name: 'Bhimavaram', country: 'India' },
    { name: 'Daltonganj', country: 'India' },
    { name: 'Tiruvuru', country: 'India' },
    { name: 'Alappuzha', country: 'India' },
    { name: 'Barasat', country: 'India' },
    { name: 'Madhubani', country: 'India' },
    { name: 'Baraut', country: 'India' },
    { name: 'Udgir', country: 'India' },
    { name: 'Basirhat', country: 'India' },
    { name: 'Bhuj', country: 'India' },
    { name: 'Chinsurah', country: 'India' },
    { name: 'Mansa', country: 'India' },
    { name: 'Kaithal', country: 'India' },
    { name: 'Ratnagiri', country: 'India' },
    { name: 'Rabkavi Banhatti', country: 'India' },
    { name: 'Kullu', country: 'India' },
    { name: 'Rajgarh', country: 'India' },
    { name: 'Phagwara', country: 'India' },
    { name: 'Bahraich', country: 'India' },
    { name: 'Gokak', country: 'India' },
    { name: 'Bongaigaon City', country: 'India' },
    { name: 'Palwal', country: 'India' },
    { name: 'Gadwal', country: 'India' },
    { name: 'Kailasahar', country: 'India' },
    { name: 'Sawai Madhopur', country: 'India' },
    { name: 'Bhawanipatna', country: 'India' },
    { name: 'Kohima', country: 'India' },
    { name: 'Palanpur', country: 'India' },
    { name: 'Kavaratti', country: 'India' },
    { name: 'Silvassa', country: 'India' },
    { name: 'Jowai', country: 'India' },
    { name: 'Kavaratti', country: 'India' },
    { name: 'Silvassa', country: 'India' },
    { name: 'Jowai', country: 'India' },
    { name: 'Tezpur', country: 'India' },
    { name: 'Barpeta', country: 'India' },
    { name: 'Nawalgarh', country: 'India' },
    { name: 'Phek', country: 'India' },
    { name: 'Kapurthala', country: 'India' },
    { name: 'Chhindwara', country: 'India' },
    { name: 'Sandila', country: 'India' },
    { name: 'Karnal', country: 'India' },
    { name: 'Tindivanam', country: 'India' },
    { name: 'Kathua', country: 'India' },
    { name: 'Jalor', country: 'India' },
    { name: 'Port Blair', country: 'India' },
    { name: 'Tezpur', country: 'India' },
    { name: 'Karur', country: 'India' },
    { name: 'Sunam', country: 'India' },
    { name: 'Udhagamandalam', country: 'India' },
    { name: 'Janjgir', country: 'India' },
    { name: 'Kannur', country: 'India' },
    { name: 'Anantnag', country: 'India' },
    { name: 'Karaikal', country: 'India' },
    { name: 'Dholka', country: 'India' },
    { name: 'Devanhalli', country: 'India' },
    { name: 'Yanam', country: 'India' },
    { name: 'Ambikapur', country: 'India' },
    { name: 'Bapatla', country: 'India' },
    { name: 'Fazilka', country: 'India' },
    { name: 'Kolar', country: 'India' },
    { name: 'Bagalkot', country: 'India' },
    { name: 'Bhimunipatnam', country: 'India' },
    { name: 'Dasarahalli', country: 'India' },
    { name: 'Madikeri', country: 'India' },
    { name: 'Rajpipla', country: 'India' },
    { name: 'Khategaon', country: 'India' },
    { name: 'Kamareddy', country: 'India' },
    { name: 'Sankeshwara', country: 'India' },
    { name: 'Nalbari', country: 'India' },
    { name: 'Karwar', country: 'India' },
    { name: 'Siddipet', country: 'India' },
    { name: 'Arsikere', country: 'India' },
    { name: 'Sanduru', country: 'India' },
    { name: 'Shamsabad, Agra', country: 'India' },
    { name: 'Pathri', country: 'India' },
    { name: 'Koyilandy', country: 'India' },
    { name: 'Samalkot', country: 'India' },
    { name: 'Nandigama', country: 'India' },
    { name: 'Ponnani', country: 'India' },
    { name: 'Hospet', country: 'India' },
    { name: 'Mettupalayam', country: 'India' },
    { name: 'Chirala', country: 'India' },
    { name: 'Shahabad, Hardoi', country: 'India' },
    { name: 'Jharsuguda', country: 'India' },
    { name: 'Changanassery', country: 'India' },
    { name: 'Khowai', country: 'India' },
    { name: 'Kendrapara', country: 'India' },
    { name: 'Kalpetta', country: 'India' },
    { name: 'Jaora', country: 'India' },
    { name: 'Mahalingapura', country: 'India' },
    { name: 'Palakkad', country: 'India' },
    { name: 'Pattukkottai', country: 'India' },
    { name: 'Sullurpeta', country: 'India' },
    { name: 'Srikalahasti', country: 'India' },
    { name: 'Sira', country: 'India' },
    { name: 'Mundargi', country: 'India' },
    { name: 'Rajgarh', country: 'India' },
    { name: 'Umaria', country: 'India' },
    { name: 'Rupnagar', country: 'India' },
    { name: 'Perumbavoor', country: 'India' },
    { name: 'Nirmal', country: 'India' },
    { name: 'Pithoragarh', country: 'India' },
    { name: 'Ponnur', country: 'India' },
    { name: 'Thanjavur', country: 'India' },
    { name: 'Jhargram', country: 'India' },
    { name: 'Kamareddy', country: 'India' },
    { name: 'Manuguru', country: 'India' },
    { name: 'Lunawada', country: 'India' },
    { name: 'Mangrol', country: 'India' },
    { name: 'Shahade', country: 'India' },
    { name: 'Sojat', country: 'India' },
    { name: 'Noorpur', country: 'India' },
    { name: 'Paravoor', country: 'India' },
    { name: 'Sumerpur', country: 'India' },
    { name: 'Uran Islampur', country: 'India' },
    { name: 'Manachanallur', country: 'India' },
    { name: 'Pithapuram', country: 'India' },
    { name: 'Chikmagalur', country: 'India' },
    { name: 'Cherthala', country: 'India' },
    { name: 'Alur', country: 'India' },
    { name: 'Giddalur', country: 'India' },
    { name: 'Bobbili', country: 'India' },
    { name: 'Lakheri', country: 'India' },
    { name: 'Nainital', country: 'India' },
    { name: 'Sonamukhi', country: 'India' },
    { name: 'Alleppey', country: 'India' },
    { name: 'Lachhmangarh', country: 'India' },
    { name: 'Bapatla', country: 'India' },
    { name: 'Punganur', country: 'India' },
    { name: 'Kot Kapura', country: 'India' },
    { name: 'Macherla', country: 'India' },
    { name: 'Rabkavi', country: 'India' },
    { name: 'Cuddapah', country: 'India' },
    { name: 'Balangir', country: 'India' },
    { name: 'Narasapuram', country: 'India' },
    { name: 'Nuzvid', country: 'India' },
    { name: 'Bangaon', country: 'India' },
    { name: 'Kadi', country: 'India' },
    { name: 'Gauribidanur', country: 'India' },
    { name: 'Rayadurg', country: 'India' },
    { name: 'Halisahar', country: 'India' },
    { name: 'Changanassery', country: 'India' },
    { name: 'Palani', country: 'India' },
    { name: 'Nagari', country: 'India' },
    { name: 'Amini', country: 'India' },
    { name: 'Gobindgarh', country: 'India' },
    { name: 'Tiruppur', country: 'India' },
    { name: 'Tamluk', country: 'India' },
    { name: 'Ranibennur', country: 'India' },
    { name: 'Kavaratti', country: 'India' },
    { name: 'Kovvur', country: 'India' },
    { name: 'Junagarh', country: 'India' },
    { name: 'Manjhanpur', country: 'India' },
    { name: 'Pandharpur', country: 'India' },
    { name: 'Dumka', country: 'India' },
    { name: 'Margao', country: 'India' },
    { name: 'Rajahmundry', country: 'India' },
    { name: 'Thodupuzha', country: 'India' },
    { name: 'Bulandshahr', country: 'India' },
    { name: 'Pachora', country: 'India' },
    { name: 'Rath', country: 'India' },
    { name: 'Dhenkanal', country: 'India' },
    { name: 'Sivakasi', country: 'India' },
    { name: 'Khambhat', country: 'India' },
    { name: 'Erode', country: 'India' },
    { name: 'Gondal', country: 'India' },
    { name: 'Sirsilla', country: 'India' },
    { name: 'Dhamtari', country: 'India' },
    { name: 'Kottagudem', country: 'India' },
    { name: 'Ashoknagar', country: 'India' },
    { name: 'Tiruvalla', country: 'India' },
    { name: 'Sehore', country: 'India' },
    { name: 'Mahad', country: 'India' },
    { name: 'Seoni', country: 'India' },
    { name: 'Uttarkashi', country: 'India' },
    { name: 'Nalbari', country: 'India' },
    { name: 'Pattukkottai', country: 'India' },
    { name: 'Nedumangad', country: 'India' },
    { name: 'Bapatla', country: 'India' },
    { name: 'Nabadwip', country: 'India' },
    { name: 'Godda', country: 'India' },
    { name: 'Anakapalle', country: 'India' },
    { name: 'Chilakaluripet', country: 'India' },
    { name: 'Kapadvanj', country: 'India' },
    { name: 'Dhenkanal', country: 'India' },
    { name: 'Darjiling', country: 'India' },
    { name: 'Narasapur', country: 'India' },
    { name: 'Shahpur', country: 'India' },
    { name: 'Thiruthani', country: 'India' },
    { name: 'Ladnu', country: 'India' },
    { name: 'Sivaganga', country: 'India' },
    { name: 'Pattukkottai', country: 'India' },
    { name: 'Gokak', country: 'India' },
    { name: 'Mahad', country: 'India' },
    { name: 'Karimganj', country: 'India' },
    { name: 'Khambhat', country: 'India' },
    { name: 'Srinivaspur', country: 'India' },
    { name: 'Palwancha', country: 'India' },
    { name: 'Wanaparthy', country: 'India' },
    { name: 'Tiruvuru', country: 'India' },
    { name: 'Gohana', country: 'India' },
    { name: 'Gobichettipalayam', country: 'India' },
    { name: 'Machilipatnam', country: 'India' },
    { name: 'Dum Duma', country: 'India' },
    { name: 'Pithapuram', country: 'India' },
    { name: 'Pithampur', country: 'India' },
    { name: 'Rajahmundry', country: 'India' },
    { name: 'Ranaghat', country: 'India' },
    { name: 'Ratlam', country: 'India' },
    { name: 'Shahabad', country: 'India' },
    { name: 'Sirhind', country: 'India' },
    { name: 'Shimoga', country: 'India' },
    { name: 'Shivpuri', country: 'India' },
    { name: 'Singrauli', country: 'India' },
    { name: 'Sivaganga', country: 'India' },
    { name: 'Srivilliputhur', country: 'India' },
    { name: 'Sri Ganganagar', country: 'India' },
    { name: 'Sultanpur', country: 'India' },
    { name: 'Sumerpur', country: 'India' },
    { name: 'Suratgarh', country: 'India' },
    { name: 'Tarakeswar', country: 'India' },
    { name: 'Tarana', country: 'India' },
    { name: 'Tarn Taran', country: 'India' },
    { name: 'Tharad', country: 'India' },
    { name: 'Thirumangalam', country: 'India' },
    { name: 'Thirupuvanam', country: 'India' },
    { name: 'Tiruttani', country: 'India' },
    { name: 'Trivandrum', country: 'India' },
    { name: 'Tufanganj', country: 'India' },
    { name: 'Tuljapur', country: 'India' },
    { name: 'Tulsipur', country: 'India' },
    { name: 'Udaipur', country: 'India' },
    { name: 'Udaipurwati', country: 'India' },
    { name: 'Udgir', country: 'India' },
    { name: 'Ujhani', country: 'India' },
    { name: 'Umarkhed', country: 'India' },
    { name: 'Umbergaon', country: 'India' },
    { name: 'Upleta', country: 'India' },
    { name: 'Uran', country: 'India' },
    { name: 'Uravakonda', country: 'India' },
    { name: 'Vadnagar', country: 'India' },
    { name: 'Valsad', country: 'India' },
    { name: 'Vandavasi', country: 'India' },
    { name: 'Vaniyambadi', country: 'India' },
    { name: 'Vedaranyam', country: 'India' },
    { name: 'Vijainagar, Ajmer', country: 'India' },
    { name: 'Vijapur', country: 'India' },
    { name: 'Vikramasingapuram', country: 'India' },
    { name: 'Viluppuram', country: 'India' },
    { name: 'Virudhachalam', country: 'India' },
    { name: 'Virudhunagar', country: 'India' },
    { name: 'Visnagar', country: 'India' },
    { name: 'Viswanatham', country: 'India' },
    { name: 'Vita', country: 'India' },
    { name: 'Wadgaon Road', country: 'India' },
    { name: 'Wadhwan', country: 'India' },
    { name: 'Wadi', country: 'India' },
    { name: 'Wai', country: 'India' },
    { name: 'Wankaner', country: 'India' },
    { name: 'Wara Seoni', country: 'India' },
    { name: 'Warhapur', country: 'India' },
    { name: 'Warud', country: 'India' },
    { name: 'Washim', country: 'India' },
    { name: 'Wokha', country: 'India' },
    { name: 'Yadgir', country: 'India' },
    { name: 'Yawal', country: 'India' },
    { name: 'Yellandu', country: 'India' },
    { name: 'Yemmiganur', country: 'India' },
    { name: 'Yerraguntla', country: 'India' },
    { name: 'Yevla', country: 'India' },
    { name: 'Zira', country: 'India' },
    { name: 'Zirakpur', country: 'India' },
    { name: 'Zunheboto', country: 'India' }


];

