export const docCategories = [
    "Driver's License",
    "National ID Card",
    "Military ID",
    "Employee ID Card",
    "PAN Card",
    "Business License",
    "Partnership Agreement",
    "Financial Statements",
    "Business Visa",
    "Work Visa",
    "Investor Visa",
    "Tourist Visa",
    "Business Visa",
    "Student Visa",
    "Work Visa",
    "Transit Visa",
    "Family Visa",
    "Spouse Visa",
    "Dependent Visa",
    "Exchange Visitor Visa",
    "Diplomatic Visa",
    "Official Visa",
    "Residence Visa",
  "Retirement Visa",
  "Investor Visa",
  "Refugee Visa",
  "Asylum Visa",
  "Humanitarian Visa",
  "Medical Visa",
  "Pilgrimage Visa",
  "Sports Visa",
  "Crew Visa",
  "Journalist Visa",
  "Artist Visa",
  "Scholar Visa",
  "Research Visa",
  "Volunteer Visa",
  "Retreat Visa",
  "Retreat Visa"
  ]
   